### PR TITLE
Used posix path for declaration content

### PR DESCRIPTION
**Pull request by skrigs**
Supports use of the plugin on windows by converting the output to a posix path

### CODE REVIEW

**Comment by DrFrankenstein** [comment]
+1 for merging this; it would help us here.

**Review by menisck — APPROVED** [review]

**Comment by abarke** [comment]
Merge it 🙏

**Review by aleclarson — APPROVED** [review]

**Comment by aleclarson** [comment]
Available in v1.0.4

**Comment by abarke** [comment]
Many thanks @aleclarson!

**Comment by abarke** [comment]
Works on my Window rig now @skrigs thanks for you contrib 👏

**Pull request merged**
